/**
 * Reactive-Documents 📗
 * 
 * V1.0.0 Release Notes
 * 
 * Interfaces / Components
 * 
 * Document (renders every children (mostly like <div />)) ✅
 * Text (For writing text) ✅
 * List (Main component for rendering bullet and number type list items) ✅
 * BulletItem ✅
 * ListItem ✅
 * Hr (horizontal line) ✅
 * PageBreak (page break) ✅
 * LineBreak (line break) ✅
 * Table (rendering tables) ✅
 * Header ✅
 * Footer ✅
 * Image ✅
 * Error handling
 * Documentation 
 * 
 * Styling
 * 
 * Parse the style object ✅
 * apply the styles to the text component (each child) ✅
 * align the text component with align prop ✅
 * 
 */
